#!/usr/bin/env node
import { logger } from './utils/logger.js';
import { validateConfig } from './config/index.js';
import { PatchOpsServer } from './api/server.js';
import { PatchAnalyzer } from './patch-logic/analyzer.js';
import { GitHubBot } from './github-bot/client.js';
import type { Vulnerability, RepoContext } from './types/index.js';

async function runServer() {
  console.log('PatchOps server: runServer function called.');
  logger.info('🚀 Starting PatchOps server...');
  validateConfig();
  
  const server = new PatchOpsServer();
  server.start();
}

async function runDemo() {
  logger.info('🎬 Running PatchOps demo...');
  validateConfig();
  
  const analyzer = new PatchAnalyzer();
  const github = new GitHubBot();
  
  const demoVulnerability: Vulnerability = {
    id: 'CVE-2020-28168',
    packageName: 'axios',
    currentVersion: '0.19.0',
    severity: 'high',
    cvssScore: 7.5,
    description: 'Server-Side Request Forgery (SSRF) vulnerability in axios',
    affectedVersions: '<0.21.1',
    fixedVersions: '>=0.21.1',
    references: [
      'https://nvd.nist.gov/vuln/detail/CVE-2020-28168',
      'https://github.com/axios/axios/releases/tag/v0.21.1',
    ],
  };

  const demoContext: RepoContext = {
    owner: 'Nightwolf7570',
    repo: 'patchops-demo-vulnerable',
    defaultBranch: 'main',
    packageManager: 'npm',
    manifestPath: 'package.json',
    lockfilePath: 'package-lock.json',
  };

  // Step 1: Analyze
  logger.info('\n📊 Step 1: Analyzing vulnerability...');
  const plan = await analyzer.analyze(demoVulnerability, demoContext, ['index.js']);
  
  logger.info(`   Threat Score: ${plan.analysis.threatScore}/100`);
  logger.info(`   Recommended: ${plan.analysis.recommendedVersion}`);
  logger.info(`   Breaking Changes: ${plan.migration.breakingChanges.length}`);
  
  // Step 2: Create PR
  logger.info('\n🔀 Step 2: Creating pull request...');
  
  const title = `Security: Update ${demoVulnerability.packageName} to ${plan.analysis.recommendedVersion} (${demoVulnerability.id})`;
  
  const body = `## 🔒 Security Patch: ${demoVulnerability.id}

### 📋 Vulnerability Details
- **Package:** ${demoVulnerability.packageName}
- **Current Version:** ${demoVulnerability.currentVersion}
- **Recommended Version:** ${plan.analysis.recommendedVersion}
- **Severity:** ${demoVulnerability.severity.toUpperCase()}
- **Threat Score:** ${plan.analysis.threatScore}/100

### 🎯 Impact Analysis
${plan.evidence.isAffected ? '✅ **Repository is affected**' : '⚠️ **Repository may be affected**'}

${plan.evidence.reason}

### 📊 Threat Assessment
${plan.analysis.threatRationale}

### 🛠️ Migration Plan

#### Breaking Changes
${plan.migration.breakingChanges.map(bc => `- ${bc}`).join('\n')}

#### Testing Checklist
${plan.migration.testChecklist.map(item => `- [ ] ${item}`).join('\n')}

---
*Generated by PatchOps*`;

  const pr = await github.createPatchPR(
    demoContext,
    demoVulnerability.packageName,
    plan.analysis.recommendedVersion,
    title,
    body
  );
  
  logger.info(`\n✅ Demo complete!`);
  logger.info(`   PR #${pr.number}: ${pr.url}`);
  logger.info(`   Branch: ${pr.branch}`);
}

async function main() {
  console.log('PatchOps: main function started.');
  const args = process.argv.slice(2);
  const command = args[0];

  try {
    switch (command) {
      case 'server':
        await runServer();
        break;
      
      case 'demo':
        await runDemo();
        break;
      
      default:
        logger.info('🚀 PatchOps - Autonomous Dependency Guardian\n');
        logger.info('Usage:');
        logger.info('  npm start server    - Start API server');
        logger.info('  npm start demo      - Run demo (analyze + create PR)');
        logger.info('\nAPI Endpoints (when server is running):');
        logger.info('  GET  /health              - Health check');
        logger.info('  POST /analyze             - Analyze vulnerability');
        logger.info('  POST /process-vulnerability - Full workflow');
        logger.info('  POST /demo/axios          - Quick axios demo');
        break;
    }
  } catch (error) {
    logger.error('Failed:', error);
    process.exit(1);
  }
}

main();
